### PR TITLE
Add client functionality for synonym management

### LINKED ISSUE #28: Client should be able to manage synonyms
The python client should have the ability to list, get, create, update and delete synonyms on an engine using the following app search endpoints.

`GET /api/as/v1/engines/{ENGINE_NAME}/synonyms`
`GET /api/as/v1/engines/{ENGINE_NAME}/synonyms/{SYNONYM_SET_ID}`
`POST /api/as/v1/engines/{ENGINE_NAME}/synonyms`
`PUT /api/as/v1/engines/{ENGINE_NAME}/synonyms/{SYNONYM_SET_ID}`
`DELETE /api/as/v1/engines/{ENGINE_NAME}/synonyms/{SYNONYM_SET_ID}`

### PR DESCRIPTION
**Pull request by CorrosiveKid**
Add functionality to list, get, create, update and delete synonym sets via the client.

Closes #28

### CODE REVIEW

**Comment by CorrosiveKid** [comment]
@JasonStoltz Please have a look when you have some time 😊

**Comment by JasonStoltz** [comment]
Thank you so much for the contribution @CorrosiveKid. You caught us at the worst possible time, we *just* moved this repository to here: https://github.com/elastic/app-search-python and were about to archive this repository. I'm not sure that we'll be able to merge this PR. Id be happy to merge it if you are able to redirect the PR to the new repository.

**Comment by CorrosiveKid** [comment]
@JasonStoltz Sure, will do!

**Comment by JasonStoltz** [comment]
Client is deprecated, closing this PR.

**Pull request closed without merging**
